import { createHash } from "node:crypto";
import {
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  rm,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const ENTRY = path.join(
  ROOT,
  "packages",
  "federated-bim-surface",
  "src",
  "package-entry.mjs",
);
const OUTPUT = path.join(
  ROOT,
  "packages",
  "federated-bim-surface",
  "runtime",
  "index.mjs",
);

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

async function createBundle(output) {
  await mkdir(path.dirname(output), { recursive: true });
  await build({
    banner: {
      js:
        "// Generated by scripts/build-federated-bim-surface-v0.3.mjs. " +
        "MPL-2.0; do not edit directly.",
    },
    bundle: true,
    entryPoints: [ENTRY],
    format: "esm",
    legalComments: "none",
    minify: false,
    outfile: output,
    platform: "neutral",
    sourcemap: false,
    target: ["es2022"],
  });
}

async function generatedBundle() {
  const temporary = await mkdtemp(
    path.join(tmpdir(), "bim-explorer-federated-surface-v03-"),
  );
  const output = path.join(temporary, "index.mjs");
  await createBundle(output);
  return { temporary, output };
}

export async function checkFederatedBimSurfaceV03Bundle() {
  const generated = await generatedBundle();
  try {
    const [current, expected] = await Promise.all([
      readFile(generated.output),
      readFile(OUTPUT),
    ]);
    if (!current.equals(expected)) {
      throw new Error(
        "Federated BIM surface v0.3 runtime is stale; rebuild it",
      );
    }
    process.stdout.write(
      `Federated BIM surface v0.3 bundle check passed: ` +
        `${expected.byteLength} bytes, sha256 ${sha256(expected)}\n`,
    );
    return Object.freeze({
      byteLength: expected.byteLength,
      sha256: sha256(expected),
    });
  } finally {
    await rm(generated.temporary, { force: true, recursive: true });
  }
}

export async function buildFederatedBimSurfaceV03Bundle() {
  const generated = await generatedBundle();
  try {
    await copyFile(generated.output, OUTPUT);
  } finally {
    await rm(generated.temporary, { force: true, recursive: true });
  }
  const body = await readFile(OUTPUT);
  return Object.freeze({
    byteLength: body.byteLength,
    sha256: sha256(body),
  });
}

async function main() {
  if (
    process.argv.length === 3 &&
    process.argv[2] === "--check"
  ) {
    await checkFederatedBimSurfaceV03Bundle();
    return;
  }
  if (process.argv.length !== 2) {
    throw new TypeError(
      "usage: node scripts/build-federated-bim-surface-v0.3.mjs " +
        "[--check]",
    );
  }
  const result = await buildFederatedBimSurfaceV03Bundle();
  process.stdout.write(
    `Federated BIM surface v0.3 bundle built: ` +
      `${result.byteLength} bytes, sha256 ${result.sha256}\n`,
  );
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  await main();
}
